### PR TITLE
PLEASE READ DESC BEFORE MERGE | base terrain tile expansion

### PR DESCRIPTION
**Pull request by KBraid**
i believe making tiles 0-11 for plains and snow twice as common as tiles 12-21 would be pleasing, but i'm not entirely sure how the code for randomizing tiles works so i can not make it so myself

### CODE REVIEW

**Comment by Robosturm** [comment]
Code ist angepasst, aber es sieht mit 1/3 2/3 meines erachtens nicht gut aus.
Meines erachtens ist der Farbkontrast zu groß:
grafik

**Comment by KBraid** [comment]
another solution i can think of is just to add three more colours to the palette so that the AWDS and AW4 can keep their full range while the rest of the palettes simply hide it with a single colour

**Comment by KBraid** [comment]
i'll do that then, though i still think the 1/3 2/3 will still be necessary grass and snow for the aw4 palette to tone down the brown

**Comment by Robosturm** [comment]
That's fine, it's also not hard to change the chances.
In general it's better to have more colours if needed instead of trying to restrict us.
Especially since the palette should over enough space

**Comment by KBraid** [comment]
would you mind shifting the ground tiles mapping from r4, r16, r28 to r100 r112, r124? make sure to leave out the shadow overlays when you do it so they stay shadows

**Comment by KBraid** [comment]
or wait i got a better idea

**Pull request merged**
