### PR TITLE
CO Text edited for clarity

### PR DESCRIPTION
**Pull request by StarBright11**
I've gone through all 76 COs in English and rewrote all of their D2D, Power, and Superpower descriptions to be as clear as possible. I also attempted to fix some of the problems with other COs (which I realize I was about 10 minutes too late at the time of this pull)

I'd appreciate if you could review the text and let me know if I missed anything!

### CODE REVIEW

**Comment by Robosturm** [comment]
@StarBright11  Thx for your hard work.
Currently the pullrequest isn't merge able cause of  conflicts. I have already fixed znadra, nana, roboandy and the beast, so please use my fixed code instead. ;) Thx.
Also you use the old code for HQ's in the co unit functions instead of                     
 buildingId === "HQ" ||
buildingId === "FORTHQ"
It should be replaced to the current code version
BUILDING.isHq(building)
Else i can't merge it ;)

One final thing you may add if you're in the mood else it's fine as it's the game supports a pseudo html support for cloring texts.
E.g. K'braid made it so that Sami's buffs are in a green color and debuffs in a red color making them easier to catch I know that's again a lot of work, So if you don't want to invest that time it's fine as it's.

**Comment by StarBright11** [comment]
Not sure why Git hates that one specific line of text for Zandra, but otherwise the merge conflicts should be fixed!

As for your other suggestion, I'm thinking of doing something in the future similar to what someone did for Julia - Check to see if the D2D does anything and if not, replace the text with a simple "Global Effects: None". If I get to that soon I might look more into doing the text coloring then. The other weird part would be figuring out how to color the +0% bonuses, but I'm sure that's not a huge deal.

**Comment by StarBright11** [comment]
Sorry, newer to coding with git, wasn't aware I could make the fix myself.

**Comment by Robosturm** [comment]
@StarBright11 All fine, Getting used to git takes some time.

One final think with what bane should i credit you in game?

**Comment by StarBright11** [comment]
Thank you! Would you mind crediting me as "Star Bright" in game?

**Pull request merged**
