### PR TITLE
CO descriptions update (Orange Star)

### PR DESCRIPTION
**Pull request by KBraid**

### CODE REVIEW

**Comment by Robosturm** [comment]
@KBraid A couple of changes required here before i can merge it:
+ On a side note I'm planning to rework several things for vanilla co's which will affect the descriptions as well.
Don't use numbers in the text.
Only refer to variables used in the code aka how Andy's co description does it.
--> The reason behind this is so a mod changing the values automatically updates the description without having to rewrite it.
All values are only allowed to be relativ to 100% e.g. increasing firepower to x% cause values interact with the second co.

As mentioned the co's/vanilla co mods will get a refactoring to make the descriptions and the code easier to maintain and understand

**Comment by KBraid** [comment]
could you give an example using Max's power description done in the way you want it? i think it should give me enough context to be able to do the same for all the rest.

**Comment by Robosturm** [comment]
I can, but i don't think you want to do it cause it's not always straight forward. :(
Changes to aira 3bdbbca
Changes to max 22b2e3a

It's a multi step procedure:
1) Extract the fixed values into variables.
2) Add the if (CO.isActive(co)) statement around each function for co functionality
3) Change the code for the CO's so zone and global bonus can be adjusted via variables like in 1). That's the actual complicated part
4) Change the text into 3 lines %0 1 etc. refers to the first variable in the replaceTextArgs function and return the text afterwards.

The benefit of the changes are:
No duplicated code in the vanilla co mods.
The text description matches the actual values used in the game

**Comment by Robosturm** [comment]
@KBraid  One more thing I realized.

Don't change the getCODescription  to return what the co does globally. The CO-Description is for flavor text and not for a technical description.

The technical part comes in the getLongCODescription function

**Comment by KBraid** [comment]
i've read some people complain on the discord that they want to be able to see what the co does in terms of stats without needing to go into the co's full description. this is what prompted me to make this change.

**Comment by KBraid** [comment]
aside from the location of the D2D for now, i'm finding the value insert to be not working, not sure if that's just my end.

image

and yes i did try removing the text recolouring i added, still only displays %# instead of the value to be inserted

**Comment by Robosturm** [comment]
grafik

**Comment by Robosturm** [comment]
But my guess why it's not working is that you run a vanilla mod that changes max.....

**Comment by KBraid** [comment]
image
 the line replacement seems to work for Andy's CO zone text but not for the rest for some reason

**Comment by KBraid** [comment]
finally found the cause, return needed to be replaced with var text =

**Comment by Robosturm** [comment]
As mentioned I'm currently going through the co's anyway and update how they work.
I already changed the co's in alphapetical order from adam to amy and Sabaka to Zandra.

So it's probably easier to use those co's so you don't have to scratch your head why the co's don't function....and wait till i get to jake etc.

**Comment by Robosturm** [comment]
Since I'm also including the changes for all vanilla mods and update the code for those as well.

**Comment by Robosturm** [comment]
Now only Cairn to Jugger are missing. I hope i can finish them tomorrow.
I'm also going to add a couple of test for all the co rework to make sure nothing game breaking sneaks in.

**Comment by Robosturm** [comment]
@KBraid Only Cairn Caulder and Cassidy are missing.
It should be fairly easy to adapt the texts you changed with the currently existing ones.
I also tried to have the variables named and structured so it should be easy to link them to powers, d2d or co zone effect

**Pull request merged**
